### ISSUE TITLE
Using Rollup for development

### ISSUE THREAD

**Issue by barretodavid** [steveblue/angular2-rollup#9]
This is more a question than a bug report. Why did you choose SystemJS for development and testing, and Rollup for production instead of just using Rollup in all the environments (with different configurations)? It seems harder to maintain with two different module loaders.

**Comment by steveblue** [comment]
JIT is used for local development primarily because live reload can be triggered in a fraction of the time it takes Rollup to bundle, particularly noticeable as application scales. It is possible to trigger live reload on both JIT and AOT compile. The way its setup is to make it less painful to maintain both but it may be configurable in some way to make it even more convenient.
